package exported

import (
	"encoding/json"
	"fmt"

	"github.com/safing/portbase/log"
	"github.com/safing/portmaster-android/go/engine"
	"github.com/safing/portmaster-android/go/engine/ui"
)

// DO NOT EDIT THIS FILE!
// The file was autogenerated by go/codegenv2/gen.go

func IsTunnelActive(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function IsTunnelActive panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ret0 := ui.IsTunnelActive()

	// Resolve the call. Marshal the complete response instead of formatting
	// strings into JSON; profiles, diagnostics and errors can contain quotes,
	// newlines and other characters that must be escaped.
	result, marshalErr := json.Marshal(map[string]interface{}{
		"ret0": ret0,
	})
	if marshalErr != nil {
		call.Error(fmt.Sprintf("failed to encode response: %s", marshalErr))
		return
	}
	call.ResolveJson(string(result))
}

func EnableTunnel(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function EnableTunnel panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ui.EnableTunnel()

	// Resolve the call
	call.Resolve()
}

func RestartTunnel(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function RestartTunnel panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ui.RestartTunnel()

	// Resolve the call
	call.Resolve()
}

func SPNLogin(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function SPNLogin panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Parameter username
	username, err := call.GetString("username")
	if err != nil {
		call.Error("missing username argument")
		return
	}
	// Parameter password
	password, err := call.GetString("password")
	if err != nil {
		call.Error("missing password argument")
		return
	}
	// Function call
	ret0, err1 := ui.SPNLogin(username, password)

	if err1 != nil {
		call.Error(err1.Error())
		return
	}

	// Resolve the call. Marshal the complete response instead of formatting
	// strings into JSON; profiles, diagnostics and errors can contain quotes,
	// newlines and other characters that must be escaped.
	result, marshalErr := json.Marshal(map[string]interface{}{
		"ret0": ret0,
	})
	if marshalErr != nil {
		call.Error(fmt.Sprintf("failed to encode response: %s", marshalErr))
		return
	}
	call.ResolveJson(string(result))
}

func SPNLogout(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function SPNLogout panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	err0 := ui.SPNLogout()

	if err0 != nil {
		call.Error(err0.Error())
		return
	}

	// Resolve the call
	call.Resolve()
}

func RefreshSPNUserProfile(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function RefreshSPNUserProfile panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ret0, err1 := ui.RefreshSPNUserProfile()

	if err1 != nil {
		call.Error(err1.Error())
		return
	}

	// Resolve the call. Marshal the complete response instead of formatting
	// strings into JSON; profiles, diagnostics and errors can contain quotes,
	// newlines and other characters that must be escaped.
	result, marshalErr := json.Marshal(map[string]interface{}{
		"ret0": ret0,
	})
	if marshalErr != nil {
		call.Error(fmt.Sprintf("failed to encode response: %s", marshalErr))
		return
	}
	call.ResolveJson(string(result))
}

func GetSPNUserProfile(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function GetSPNUserProfile panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ret0, err1 := ui.GetSPNUserProfile()

	if err1 != nil {
		call.Error(err1.Error())
		return
	}

	// Resolve the call. Marshal the complete response instead of formatting
	// strings into JSON; profiles, diagnostics and errors can contain quotes,
	// newlines and other characters that must be escaped.
	result, marshalErr := json.Marshal(map[string]interface{}{
		"ret0": ret0,
	})
	if marshalErr != nil {
		call.Error(fmt.Sprintf("failed to encode response: %s", marshalErr))
		return
	}
	call.ResolveJson(string(result))
}

func GetSPNStatus(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function GetSPNStatus panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ret0, err1 := ui.GetSPNStatus()

	if err1 != nil {
		call.Error(err1.Error())
		return
	}

	// Resolve the call. Marshal the complete response instead of formatting
	// strings into JSON; profiles, diagnostics and errors can contain quotes,
	// newlines and other characters that must be escaped.
	result, marshalErr := json.Marshal(map[string]interface{}{
		"ret0": ret0,
	})
	if marshalErr != nil {
		call.Error(fmt.Sprintf("failed to encode response: %s", marshalErr))
		return
	}
	call.ResolveJson(string(result))
}

func SetSPNEnabled(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function SetSPNEnabled panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Parameter enabled
	enabled, err := call.GetBool("enabled")
	if err != nil {
		call.Error("missing enabled argument")
		return
	}
	// Function call
	err0 := ui.SetSPNEnabled(enabled)

	if err0 != nil {
		call.Error(err0.Error())
		return
	}

	// Resolve the call
	call.Resolve()
}

func SetSPNExitCountry(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function SetSPNExitCountry panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Parameter country
	country, err := call.GetString("country")
	if err != nil {
		call.Error("missing country argument")
		return
	}
	// Function call
	err0 := ui.SetSPNExitCountry(country)

	if err0 != nil {
		call.Error(err0.Error())
		return
	}

	// Resolve the call
	call.Resolve()
}

func GetSPNExitCountry(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function GetSPNExitCountry panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ret0 := ui.GetSPNExitCountry()

	// Resolve the call. Marshal the complete response instead of formatting
	// strings into JSON; profiles, diagnostics and errors can contain quotes,
	// newlines and other characters that must be escaped.
	result, marshalErr := json.Marshal(map[string]interface{}{
		"ret0": ret0,
	})
	if marshalErr != nil {
		call.Error(fmt.Sprintf("failed to encode response: %s", marshalErr))
		return
	}
	call.ResolveJson(string(result))
}

func GetTunnelLastError(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function GetTunnelLastError panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ret0 := ui.GetTunnelLastError()

	// Resolve the call. Marshal the complete response instead of formatting
	// strings into JSON; profiles, diagnostics and errors can contain quotes,
	// newlines and other characters that must be escaped.
	result, marshalErr := json.Marshal(map[string]interface{}{
		"ret0": ret0,
	})
	if marshalErr != nil {
		call.Error(fmt.Sprintf("failed to encode response: %s", marshalErr))
		return
	}
	call.ResolveJson(string(result))
}

func GetLogs(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function GetLogs panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Parameter ID
	ID, err := call.GetLong("ID")
	if err != nil {
		call.Error("missing ID argument")
		return
	}
	// Function call
	ret0 := ui.GetLogs(ID)

	// Resolve the call. Marshal the complete response instead of formatting
	// strings into JSON; profiles, diagnostics and errors can contain quotes,
	// newlines and other characters that must be escaped.
	result, marshalErr := json.Marshal(map[string]interface{}{
		"ret0": ret0,
	})
	if marshalErr != nil {
		call.Error(fmt.Sprintf("failed to encode response: %s", marshalErr))
		return
	}
	call.ResolveJson(string(result))
}

func GetDebugInfoFile(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function GetDebugInfoFile panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ui.GetDebugInfoFile()

	// Resolve the call
	call.Resolve()
}

func GetDebugInfo(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function GetDebugInfo panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ret0, err1 := ui.GetDebugInfo()

	if err1 != nil {
		call.Error(err1.Error())
		return
	}

	// Resolve the call. Marshal the complete response instead of formatting
	// strings into JSON; profiles, diagnostics and errors can contain quotes,
	// newlines and other characters that must be escaped.
	result, marshalErr := json.Marshal(map[string]interface{}{
		"ret0": ret0,
	})
	if marshalErr != nil {
		call.Error(fmt.Sprintf("failed to encode response: %s", marshalErr))
		return
	}
	call.ResolveJson(string(result))
}

func Shutdown(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function Shutdown panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ui.Shutdown()

	// Resolve the call
	call.Resolve()
}

func CreateIssue(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function CreateIssue panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Parameter debugInfo
	debugInfo, err := call.GetString("debugInfo")
	if err != nil {
		call.Error("missing debugInfo argument")
		return
	}
	// Parameter genUrl
	genUrl, err := call.GetBool("genUrl")
	if err != nil {
		call.Error("missing genUrl argument")
		return
	}
	// Parameter issueRequestStr
	issueRequestStr, err := call.GetString("issueRequestStr")
	if err != nil {
		call.Error("missing issueRequestStr argument")
		return
	}
	// Function call
	ret0, err1 := ui.CreateIssue(debugInfo, genUrl, issueRequestStr)

	if err1 != nil {
		call.Error(err1.Error())
		return
	}

	// Resolve the call. Marshal the complete response instead of formatting
	// strings into JSON; profiles, diagnostics and errors can contain quotes,
	// newlines and other characters that must be escaped.
	result, marshalErr := json.Marshal(map[string]interface{}{
		"ret0": ret0,
	})
	if marshalErr != nil {
		call.Error(fmt.Sprintf("failed to encode response: %s", marshalErr))
		return
	}
	call.ResolveJson(string(result))
}

func CreateTicket(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function CreateTicket panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Parameter debugInfo
	debugInfo, err := call.GetString("debugInfo")
	if err != nil {
		call.Error("missing debugInfo argument")
		return
	}
	// Parameter ticketRequestStr
	ticketRequestStr, err := call.GetString("ticketRequestStr")
	if err != nil {
		call.Error("missing ticketRequestStr argument")
		return
	}
	// Function call
	err0 := ui.CreateTicket(debugInfo, ticketRequestStr)

	if err0 != nil {
		call.Error(err0.Error())
		return
	}

	// Resolve the call
	call.Resolve()
}

func IsGeoIPDataAvailable(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function IsGeoIPDataAvailable panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ret0, err1 := ui.IsGeoIPDataAvailable()

	if err1 != nil {
		call.Error(err1.Error())
		return
	}

	// Resolve the call. Marshal the complete response instead of formatting
	// strings into JSON; profiles, diagnostics and errors can contain quotes,
	// newlines and other characters that must be escaped.
	result, marshalErr := json.Marshal(map[string]interface{}{
		"ret0": ret0,
	})
	if marshalErr != nil {
		call.Error(fmt.Sprintf("failed to encode response: %s", marshalErr))
		return
	}
	call.ResolveJson(string(result))
}

func NewApkAvaliable(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function NewApkAvaliable panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ret0 := ui.NewApkAvaliable()

	// Resolve the call. Marshal the complete response instead of formatting
	// strings into JSON; profiles, diagnostics and errors can contain quotes,
	// newlines and other characters that must be escaped.
	result, marshalErr := json.Marshal(map[string]interface{}{
		"ret0": ret0,
	})
	if marshalErr != nil {
		call.Error(fmt.Sprintf("failed to encode response: %s", marshalErr))
		return
	}
	call.ResolveJson(string(result))
}

func PerformRequest(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function PerformRequest panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	ui.PerformRequest(call)
}

func DatabaseMessage(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function DatabaseMessage panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Parameter msg
	msg, err := call.GetString("msg")
	if err != nil {
		call.Error("missing msg argument")
		return
	}
	// Function call
	ui.DatabaseMessage(msg)

	// Resolve the call
	call.Resolve()
}

func SubscribeToDatabase(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function SubscribeToDatabase panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	ui.SubscribeToDatabase(call)
}

func DownloadPendingUpdates(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function DownloadPendingUpdates panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ui.DownloadPendingUpdates()

	// Resolve the call
	call.Resolve()
}

func DownloadUpdatesOnWifiConnected(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function DownloadUpdatesOnWifiConnected panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ui.DownloadUpdatesOnWifiConnected()

	// Resolve the call
	call.Resolve()
}

func IsOnWifiNetwork(call engine.PluginCall) {
	// set up recovery
	defer func() {
		// recover from panic
		panicVal := recover()
		if panicVal != nil {
			log.Errorf("ui: function IsOnWifiNetwork panicked: %s", panicVal)
			if call != nil {
				call.Error(fmt.Sprintf("function panicked: %s", panicVal))
			}
		}
	}()

	// Function call
	ret0 := ui.IsOnWifiNetwork()

	// Resolve the call. Marshal the complete response instead of formatting
	// strings into JSON; profiles, diagnostics and errors can contain quotes,
	// newlines and other characters that must be escaped.
	result, marshalErr := json.Marshal(map[string]interface{}{
		"ret0": ret0,
	})
	if marshalErr != nil {
		call.Error(fmt.Sprintf("failed to encode response: %s", marshalErr))
		return
	}
	call.ResolveJson(string(result))
}
