package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"text/template"
	"unicode"
)

const javaFileTemplate = `package io.safing.portmaster.android.ui;

// DO NOT EDIT THIS FILE!
// The file was autogenerated by go/codegen/gen.go

import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

import org.json.JSONException;

@CapacitorPlugin(name = "GoBridge")
public class GoBridge extends Plugin {
%s
	public void notifyListener(String name, String data) throws JSONException {
		notifyListeners(name, new JSObject(data));
	}
}
`

const javaMethodTemplate = `
	@PluginMethod()
	public void {{.Name}}(PluginCall call) {
		exported.Exported.{{gomobileName .Name}}(new GoPluginCall(this, call));
	}
`

// gomobileJavaName mirrors the Java naming convention used by modern gobind:
// ordinary exported names lower-case their first letter (IsTunnelActive ->
// isTunnelActive), while a leading Go initialism is lower-cased as a unit
// (SPNLogin -> spnLogin, URLValue -> urlValue).
func gomobileJavaName(name string) string {
	if name == "" {
		return name
	}

	runes := []rune(name)
	prefixEnd := 1
	for prefixEnd < len(runes) && unicode.IsUpper(runes[prefixEnd]) {
		// The last uppercase rune before a lowercase word starts that word,
		// rather than belonging to the initialism: SPNLogin => SPN + Login.
		if prefixEnd+1 < len(runes) && unicode.IsLower(runes[prefixEnd+1]) {
			break
		}
		prefixEnd++
	}

	prefix := strings.ToLower(string(runes[:prefixEnd]))
	return prefix + string(runes[prefixEnd:])
}

func writeToJavaFile(filename string, functions []Func) {
	javaFile, err := os.Create(filename)
	if err != nil {
		fmt.Printf("Failed to create file: %s", err)
		return
	}
	defer javaFile.Close()

	javaTmpl := template.New("JavaFunctionTemplate")
	javaTmpl.Funcs(template.FuncMap{
		"gomobileName": gomobileJavaName,
	})
	_, err = javaTmpl.Parse(javaMethodTemplate)
	if err != nil {
		fmt.Printf("Failed to parse template: %s", err)
		return
	}

	buf := new(bytes.Buffer)

	for _, r := range functions {
		javaTmpl.Execute(buf, r)
	}

	_, err = javaFile.WriteString(fmt.Sprintf(javaFileTemplate, buf.String()))
	if err != nil {
		fmt.Printf("Failed to write to file: %s", err)
		return
	}
}
